
package defaultnamespace.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.4.5
 * Tue Dec 28 19:22:14 GMT 2021
 * Generated source version: 3.4.5
 */

@XmlRootElement(name = "bookingsByEmail", namespace = "http://utility.hotel.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bookingsByEmail", namespace = "http://utility.hotel.com/")

public class BookingsByEmail {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

}

