
package defaultnamespace.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.4.5
 * Tue Dec 28 17:51:58 GMT 2021
 * Generated source version: 3.4.5
 */

@XmlRootElement(name = "getRoomFloorAndCapacityResponse", namespace = "http://utility.hotel.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getRoomFloorAndCapacityResponse", namespace = "http://utility.hotel.com/")

public class GetRoomFloorAndCapacityResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

