
package defaultnamespace.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.4.5
 * Tue Dec 28 17:51:58 GMT 2021
 * Generated source version: 3.4.5
 */

@XmlRootElement(name = "getRoomFloorAndCapacity", namespace = "http://utility.hotel.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getRoomFloorAndCapacity", namespace = "http://utility.hotel.com/")

public class GetRoomFloorAndCapacity {

    @XmlElement(name = "arg0")
    private int arg0;

    public int getArg0() {
        return this.arg0;
    }

    public void setArg0(int newArg0)  {
        this.arg0 = newArg0;
    }

}

