
package defaultnamespace.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.4.5
 * Mon Dec 27 22:12:03 WET 2021
 * Generated source version: 3.4.5
 */

@XmlRootElement(name = "listRoomsResponse", namespace = "http://utility.hotel.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "listRoomsResponse", namespace = "http://utility.hotel.com/")

public class ListRoomsResponse {


}

