
package defaultnamespace.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.4.5
 * Tue Dec 28 13:50:51 WET 2021
 * Generated source version: 3.4.5
 */

@XmlRootElement(name = "ping", namespace = "http://utility.hotel.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ping", namespace = "http://utility.hotel.com/")

public class Ping {


}

