
package com.hotel.utility;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2021-12-28T19:31:04.201Z
 * Generated source version: 3.4.5
 *
 */
public final class HotelUtility_HotelUtilityPort_Client {

    private static final QName SERVICE_NAME = new QName("http://utility.hotel.com/", "HotelUtilityService");

    private HotelUtility_HotelUtilityPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = HotelUtilityService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        HotelUtilityService ss = new HotelUtilityService(wsdlURL, SERVICE_NAME);
        HotelUtility port = ss.getHotelUtilityPort();

        {
        System.out.println("Invoking listRooms...");
        java.lang.String _listRooms_arg0 = "_listRooms_arg0546681987";
        java.lang.String _listRooms_arg1 = "_listRooms_arg11257011105";
        java.util.List<java.lang.String> _listRooms__return = port.listRooms(_listRooms_arg0, _listRooms_arg1);
        System.out.println("listRooms.result=" + _listRooms__return);


        }
        {
        System.out.println("Invoking registerUser...");
        java.lang.String _registerUser_arg0 = "_registerUser_arg0-404740394";
        java.lang.String _registerUser_arg1 = "_registerUser_arg1-1650242665";
        boolean _registerUser__return = port.registerUser(_registerUser_arg0, _registerUser_arg1);
        System.out.println("registerUser.result=" + _registerUser__return);


        }
        {
        System.out.println("Invoking bookRoom...");
        java.lang.String _bookRoom_arg0 = "_bookRoom_arg01176122684";
        java.lang.String _bookRoom_arg1 = "_bookRoom_arg1-668168908";
        java.lang.String _bookRoom_arg2 = "_bookRoom_arg2730210045";
        int _bookRoom_arg3 = -612060376;
        int _bookRoom_arg4 = 1409126469;
        java.lang.String _bookRoom__return = port.bookRoom(_bookRoom_arg0, _bookRoom_arg1, _bookRoom_arg2, _bookRoom_arg3, _bookRoom_arg4);
        System.out.println("bookRoom.result=" + _bookRoom__return);


        }
        {
        System.out.println("Invoking bookingsByEmail...");
        java.lang.String _bookingsByEmail_arg0 = "_bookingsByEmail_arg01141208693";
        java.util.List<java.lang.String> _bookingsByEmail__return = port.bookingsByEmail(_bookingsByEmail_arg0);
        System.out.println("bookingsByEmail.result=" + _bookingsByEmail__return);


        }
        {
        System.out.println("Invoking loginUser...");
        java.lang.String _loginUser_arg0 = "_loginUser_arg0-1650960756";
        java.lang.String _loginUser_arg1 = "_loginUser_arg1-1562153104";
        boolean _loginUser__return = port.loginUser(_loginUser_arg0, _loginUser_arg1);
        System.out.println("loginUser.result=" + _loginUser__return);


        }
        {
        System.out.println("Invoking getRoomFloorAndCapacity...");
        int _getRoomFloorAndCapacity_arg0 = 817124996;
        java.lang.String _getRoomFloorAndCapacity__return = port.getRoomFloorAndCapacity(_getRoomFloorAndCapacity_arg0);
        System.out.println("getRoomFloorAndCapacity.result=" + _getRoomFloorAndCapacity__return);


        }
        {
        System.out.println("Invoking cancelReservation...");
        java.lang.String _cancelReservation_arg0 = "_cancelReservation_arg02000793633";
        boolean _cancelReservation__return = port.cancelReservation(_cancelReservation_arg0);
        System.out.println("cancelReservation.result=" + _cancelReservation__return);


        }

        System.exit(0);
    }

}
