
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.hotel.utility;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2021-12-28T19:31:04.287Z
 * Generated source version: 3.4.5
 *
 */

@javax.jws.WebService(
                      serviceName = "HotelUtilityService",
                      portName = "HotelUtilityPort",
                      targetNamespace = "http://utility.hotel.com/",
                      wsdlLocation = "http://localhost:8080/HotelUtility/services/HotelUtilityPort?wsdl",
                      endpointInterface = "com.hotel.utility.HotelUtility")

public class HotelUtilityPortImpl implements HotelUtility {

    private static final Logger LOG = Logger.getLogger(HotelUtilityPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.hotel.utility.HotelUtility#listRooms(java.lang.String arg0, java.lang.String arg1)*
     */
    public java.util.List<java.lang.String> listRooms(java.lang.String arg0, java.lang.String arg1) {
        LOG.info("Executing operation listRooms");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.util.List<java.lang.String> _return = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnVal1 = "_returnVal1020312887";
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hotel.utility.HotelUtility#registerUser(java.lang.String arg0, java.lang.String arg1)*
     */
    public boolean registerUser(java.lang.String arg0, java.lang.String arg1) {
        LOG.info("Executing operation registerUser");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hotel.utility.HotelUtility#bookRoom(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, int arg3, int arg4)*
     */
    public java.lang.String bookRoom(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, int arg3, int arg4) {
        LOG.info("Executing operation bookRoom");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        System.out.println(arg4);
        try {
            java.lang.String _return = "_return-1497603516";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hotel.utility.HotelUtility#bookingsByEmail(java.lang.String arg0)*
     */
    public java.util.List<java.lang.String> bookingsByEmail(java.lang.String arg0) {
        LOG.info("Executing operation bookingsByEmail");
        System.out.println(arg0);
        try {
            java.util.List<java.lang.String> _return = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnVal1 = "_returnVal-1568995289";
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hotel.utility.HotelUtility#loginUser(java.lang.String arg0, java.lang.String arg1)*
     */
    public boolean loginUser(java.lang.String arg0, java.lang.String arg1) {
        LOG.info("Executing operation loginUser");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hotel.utility.HotelUtility#getRoomFloorAndCapacity(int arg0)*
     */
    public java.lang.String getRoomFloorAndCapacity(int arg0) {
        LOG.info("Executing operation getRoomFloorAndCapacity");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return-1522177234";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hotel.utility.HotelUtility#cancelReservation(java.lang.String arg0)*
     */
    public boolean cancelReservation(java.lang.String arg0) {
        LOG.info("Executing operation cancelReservation");
        System.out.println(arg0);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
