package com.hotel.utility;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2021-12-28T19:31:04.304Z
 * Generated source version: 3.4.5
 *
 */
@WebService(targetNamespace = "http://utility.hotel.com/", name = "HotelUtility")
@XmlSeeAlso({ObjectFactory.class})
public interface HotelUtility {

    @WebMethod
    @RequestWrapper(localName = "listRooms", targetNamespace = "http://utility.hotel.com/", className = "com.hotel.utility.ListRooms")
    @ResponseWrapper(localName = "listRoomsResponse", targetNamespace = "http://utility.hotel.com/", className = "com.hotel.utility.ListRoomsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.String> listRooms(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "registerUser", targetNamespace = "http://utility.hotel.com/", className = "com.hotel.utility.RegisterUser")
    @ResponseWrapper(localName = "registerUserResponse", targetNamespace = "http://utility.hotel.com/", className = "com.hotel.utility.RegisterUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean registerUser(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "bookRoom", targetNamespace = "http://utility.hotel.com/", className = "com.hotel.utility.BookRoom")
    @ResponseWrapper(localName = "bookRoomResponse", targetNamespace = "http://utility.hotel.com/", className = "com.hotel.utility.BookRoomResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String bookRoom(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4
    );

    @WebMethod
    @RequestWrapper(localName = "bookingsByEmail", targetNamespace = "http://utility.hotel.com/", className = "com.hotel.utility.BookingsByEmail")
    @ResponseWrapper(localName = "bookingsByEmailResponse", targetNamespace = "http://utility.hotel.com/", className = "com.hotel.utility.BookingsByEmailResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.String> bookingsByEmail(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "loginUser", targetNamespace = "http://utility.hotel.com/", className = "com.hotel.utility.LoginUser")
    @ResponseWrapper(localName = "loginUserResponse", targetNamespace = "http://utility.hotel.com/", className = "com.hotel.utility.LoginUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean loginUser(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "getRoomFloorAndCapacity", targetNamespace = "http://utility.hotel.com/", className = "com.hotel.utility.GetRoomFloorAndCapacity")
    @ResponseWrapper(localName = "getRoomFloorAndCapacityResponse", targetNamespace = "http://utility.hotel.com/", className = "com.hotel.utility.GetRoomFloorAndCapacityResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getRoomFloorAndCapacity(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "cancelReservation", targetNamespace = "http://utility.hotel.com/", className = "com.hotel.utility.CancelReservation")
    @ResponseWrapper(localName = "cancelReservationResponse", targetNamespace = "http://utility.hotel.com/", className = "com.hotel.utility.CancelReservationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean cancelReservation(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
